- hosts: all
  name: Copy image
  tasks:
    - synchronize:
        dest: "{{ zuul.executor.work_root }}/artifacts/"
        mode: pull
        src: "{{ ansible_user_dir }}/test-server"
        verify_host: true
        rsync_opts:
          - "--exclude=/*/*/"
